[package]
name = "rust_file_demo"
version = "0.1.0"
authors = ["thomas yang <ywjno.dev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
